Movie Hub/Areas/Admin/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieHub.Contracts;
using MovieHub.ViewModels;
using static MovieHub.Common.GeneralApplicationConstants;

namespace Movie_Hub.Areas.Admin.Controllers
{
    public class MovieController : BaseAdminController
    {
        private readonly IMovieService movieService;

        public MovieController(IMovieService service)
        {
            this.movieService = service;
        }
        //Add movie 
        [HttpGet]
        public async Task<IActionResult> AddMovie()
        {
            var model = await movieService.GetNewAddMovieModelAsync();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddMovie(AddMovieViewModel model)
        {
            
            await movieService.AddMovieAsync(model);
            return RedirectToAction("All", "Library");
        }





        //Show movie details
        public async Task<IActionResult> MovieDetails(Guid id)
        {
            var mdoel = await movieService.GetMovieByIdAsync(id);

            if (mdoel == null)
            {
                return RedirectToAction("All", "Library");
            }

            return View(mdoel);
        }



        //Edit movie
        [HttpGet]
        public async Task<IActionResult> EditMovie(Guid id)
        {
            var model = await movieService.GetMovieByIdForEditAsync(id);

            if (model == null || User.IsInRole(AdminRole))
            {
                return RedirectToAction("All", "Library");
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditMovie(AddMovieViewModel model)
        {

            await movieService.EditMovieAsync(model);
            return RedirectToAction("All", "Library");
        }

        //Delete movie
        public async Task<IActionResult> DeleteMovie(Guid Id)
        {
            if (User.IsInRole(AdminRole))
            {
                await movieService.DeleteMovieAsync(Id);
            }
            
            return RedirectToAction("All", "Library");
        }

    }
}

Movie Hub/Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using MovieHub.Contracts;
using static MovieHub.Common.GeneralApplicationConstants;
using MovieHub.Services;
using MovieHub.ViewModels;

namespace Movie_Hub.Controllers
{
    public class ActorController : BaseController
    {
        private readonly IActorService actorService;
        public ActorController(IActorService service)
        {
            this.actorService = service;
        }

        //Add actor
        [HttpGet]
        public async Task<IActionResult> AddActor(Guid Id)
        {
            var model = await actorService.GetNewAddActorModelAsync();

            ViewData["MovieId"] = Id;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddActor(AddActorViewModel model, Guid Id)
        {
           
            await actorService.AddActorAsync(model, Id);
            return RedirectToAction("All", "Library");
        }

        //Show actor details
        public async Task<IActionResult> ActorDetails(Guid id)
        {
            var mdoel = await actorService.GetActorByIdAsync(id);

            if (mdoel == null)
            {
                return RedirectToAction("All", "Library");
            }

            return View(mdoel);
        }

        //Edit actor
        [HttpGet]
        public async Task<IActionResult> EditActor(Guid id)
        {
            var model = await actorService.GetActorByIdForEditAsync(id);

            if (model == null || !User.IsInRole(AdminRole))
            {
                return RedirectToAction("All", "Library");
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditActor(AddActorViewModel model)
        {

            await actorService.EditActorAsync(model);
            return RedirectToAction("All", "Library");
        }
        //Delete actor
        public async Task<IActionResult> DeleteActor(Guid Id)
        {
            if (User.IsInRole(AdminRole))
            {
                await actorService.DeleteActorAsync(Id);
                
            }
            return RedirectToAction("All", "Library");
        }
    }
}

Movie Hub/Controllers/DirectorController.cs
using Microsoft.AspNetCore.Mvc;
using MovieHub.Contracts;
using MovieHub.Services;
using MovieHub.ViewModels;
using static MovieHub.Common.GeneralApplicationConstants;

namespace Movie_Hub.Controllers
{
    public class DirectorController : Controller
    {
        private readonly IDirectorService directorService;
        public DirectorController(IDirectorService service)
        {
            this.directorService = service;
        }
        

        //Add Director
        [HttpGet]
        public async Task<IActionResult> AddDirector(Guid Id)
        {
            var model = await directorService.GetNewAddDirectorModelAsync();

            ViewData["MovieId"] = Id;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddDirector(AddDirectorViewModel model, Guid Id)
        {
            
            await directorService.AddDirectorAsync(model, Id);
            return RedirectToAction("All", "Library");
        }
        //Edit director
        [HttpGet]
        public async Task<IActionResult> EditDirector(Guid id)
        {
            var model = await directorService.GetDirectorByIdForEditAsync(id);

            if (model == null || !User.IsInRole(AdminRole))
            {
                return RedirectToAction("All", "Library");
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditDirector(AddDirectorViewModel model)
        {

            await directorService.EditDirectorAsync(model);
            return RedirectToAction("All", "Library");
        }
        //Delete director
        public async Task<IActionResult> DeleteDirector(Guid Id)
        {
            if (User.IsInRole(AdminRole))
            {
                await directorService.DeleteDirectorAsync(Id);

            }
            return RedirectToAction("All", "Library");
        }
        //Show director details
        public async Task<IActionResult> DirectorDetails(Guid id)
        {
            var mdoel = await directorService.GetDirectorByIdAsync(id);

            if (mdoel == null)
            {
                return RedirectToAction("All", "Library");
            }

            return View(mdoel);
        }
    }
}

Movie Hub/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MovieHub.Contracts;
using MovieHub.Services;
using MovieHub.ViewModels;
using static MovieHub.Common.GeneralApplicationConstants;

namespace Movie_Hub.Controllers
{
    public class MovieController : BaseController
    {
        private readonly IMovieService movieService;

        public MovieController(IMovieService service)
        {
            this.movieService = service;
        }
        //Add movie 
        [HttpGet]
        public async Task<IActionResult> AddMovie()
        {
            var model = await movieService.GetNewAddMovieModelAsync();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddMovie(AddMovieViewModel model)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(model);
            //}
            await movieService.AddMovieAsync(model);
            return RedirectToAction("All","Library");
        }





        //Show movie details
        public async Task<IActionResult> MovieDetails(Guid id)
        {
            var mdoel = await movieService.GetMovieByIdAsync(id);

            if (mdoel == null)
            {
                return RedirectToAction("All", "Library");
            }

            return View(mdoel);
        }



        //Edit movie
        [HttpGet]
        public async Task<IActionResult> EditMovie(Guid id)
        {
            var model = await movieService.GetMovieByIdForEditAsync(id);

            if (model == null || !User.IsInRole(AdminRole))
            {
                return RedirectToAction("All", "Library");
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditMovie(AddMovieViewModel model)
        {

            await movieService.EditMovieAsync(model);
            return RedirectToAction("All", "Library");
        }



        //Like and Remove like
        public async Task<IActionResult> Like(Guid id)
        {
            var currentMovie = await movieService.GetMovieByIdAsync(id);

            if (currentMovie == null)
            {
                return RedirectToAction("All", "Library");
            }

            var userId = GetUserID();
            var value = await movieService.LikeMovieAsync(id, userId);
            if (value == "Done")
            {
                return RedirectToAction("Liked", "Library");
            }
            return RedirectToAction("All", "Library");

        }

        public async Task<IActionResult> RemoveLike(Guid id)
        {
            var currentEvent = await movieService.GetMovieByIdAsync(id);

            if (currentEvent == null)
            {
                return RedirectToAction("All", "Library");
            }

            var userId = GetUserID();
            await movieService.RemoveLikeMovieAsync(id, userId);
            return RedirectToAction("All", "Library");
        }

        public async Task<IActionResult> DeleteMovie(Guid Id)
        {
            if (User.IsInRole(AdminRole))
            {
                await movieService.DeleteMovieAsync(Id);
            }
            
            return RedirectToAction("All", "Library");
        }

    }
}

Movie Hub/Views/Movie/AddMovie.cshtml
@model MovieHub.ViewModels.AddMovieViewModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="AddMovie" method="post">

            @*Movie name*@
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label-add-edit">Name</label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>

           @* Movie Description*@
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit">Description</label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            @*Movie Release Date*@
             <div class="mb-3">
                <label asp-for="@Model.ReleaseDate" class="form-label-add-edit">Release Date</label>
                <input asp-for="@Model.ReleaseDate" class="form-control" aria-required="true" value="@DateTime.Now.ToString("yyyy-MM-dd H:mm")" />
                <span asp-validation-for="@Model.ReleaseDate" class="text-danger"></span>
            </div>

            @*First Category*@
             <div class="mb-3">
                <label asp-for="@Model.FirstCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.FirstCategorieId.Id" class="form-control" aria-required="true">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.FirstCategorieId.Id" class="text-danger"></span>
            </div>

            @*Second Category*@
            <div class="mb-3">
                <label asp-for="@Model.SecondCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.SecondCategorieId.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.SecondCategorieId.Id" class="text-danger"></span>
            </div>

            @*Third Category*@
             <div class="mb-3">
                <label asp-for="@Model.ThirdCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.ThirdCategorieId.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.ThirdCategorieId.Id" class="text-danger"></span>
            </div>

            @*First Reward*@
            <div class="mb-3">
                <label asp-for="@Model.FirstReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.FirstReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.FirstReward.Id" class="text-danger"></span>
            </div>

            @*Second Reward*@
            <div class="mb-3">
                <label asp-for="@Model.SecondReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.SecondReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.SecondReward.Id" class="text-danger"></span>
            </div>

            @*Third Reward*@
            <div class="mb-3">
                <label asp-for="@Model.ThirdReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.ThirdReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.ThirdReward.Id" class="text-danger"></span>
            </div>

             <div class="mb-3">
                <label asp-for="@Model.MovieLength" class="form-label-add-edit">Movie Length</label>
                <input asp-for="@Model.MovieLength" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.MovieLength" class="text-danger"></span>
            </div>

             <div class="mb-3">
                <label asp-for="@Model.StudioName" class="form-label-add-edit">Movie Studio</label>
                <input asp-for="@Model.StudioName" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.StudioName" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.ImgURL" class="form-label-add-edit">IMG url</label>
                <input asp-for="@Model.ImgURL" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImgURL" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.Budget" class="form-label-add-edit">Movie Budget</label>
                <input asp-for="@Model.Budget" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Budget" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Movie Hub/Views/Movie/EditMovie.cshtml
@model MovieHub.ViewModels.AddMovieViewModel

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form asp-action="EditMovie" method="post">

            @*Movie name*@
            <div class="mb-3">
                <label asp-for="@Model.Title" class="form-label-add-edit">Name</label>
                <input asp-for="@Model.Title" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Title" class="text-danger"></span>
            </div>

           @* Movie Description*@
            <div class="mb-3">
                <label asp-for="@Model.Description" class="form-label-add-edit">Description</label>
                <textarea asp-for="@Model.Description" class="form-control" aria-required="true" rows="5"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            @*Movie Release Date*@
             <div class="mb-3">
                <label asp-for="@Model.ReleaseDate" class="form-label-add-edit">Release Date</label>
                <input asp-for="@Model.ReleaseDate" class="form-control" aria-required="true" value="@DateTime.Now.ToString("yyyy-MM-dd H:mm")" />
                <span asp-validation-for="@Model.ReleaseDate" class="text-danger"></span>
            </div>

            @*First Category*@
             <div class="mb-3">
                <label asp-for="@Model.FirstCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.FirstCategorieId.Id" class="form-control" aria-required="true">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.FirstCategorieId.Id" class="text-danger"></span>
            </div>

            @*Second Category*@
            <div class="mb-3">
                <label asp-for="@Model.SecondCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.SecondCategorieId.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.SecondCategorieId.Id" class="text-danger"></span>
            </div>

            @*Third Category*@
             <div class="mb-3">
                <label asp-for="@Model.ThirdCategorieId.Id" class="form-label-add-edit">Category</label>
                <select asp-for="@Model.ThirdCategorieId.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Categories)
                    {
                        <option value="@type.Id">@type.Name</option>
                    }
                </select>
                <span asp-validation-for="@Model.ThirdCategorieId.Id" class="text-danger"></span>
            </div>

            @*First Reward*@
            <div class="mb-3">
                <label asp-for="@Model.FirstReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.FirstReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.FirstReward.Id" class="text-danger"></span>
            </div>

            @*Second Reward*@
            <div class="mb-3">
                <label asp-for="@Model.SecondReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.SecondReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.SecondReward.Id" class="text-danger"></span>
            </div>

            @*Third Reward*@
            <div class="mb-3">
                <label asp-for="@Model.ThirdReward.Id" class="form-label-add-edit">Award</label>
                <select asp-for="@Model.ThirdReward.Id" class="form-control" aria-required="false">
                    @foreach (var type in Model.Rewards)
                    {
                        <option value="@type.Id">@type.Title</option>
                    }
                </select>
                <span asp-validation-for="@Model.ThirdReward.Id" class="text-danger"></span>
            </div>

             <div class="mb-3">
                <label asp-for="@Model.MovieLength" class="form-label-add-edit">Movie Length</label>
                <input asp-for="@Model.MovieLength" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.MovieLength" class="text-danger"></span>
            </div>

             <div class="mb-3">
                <label asp-for="@Model.StudioName" class="form-label-add-edit">Movie Studio</label>
                <input asp-for="@Model.StudioName" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.StudioName" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.ImgURL" class="form-label-add-edit">IMG url</label>
                <input asp-for="@Model.ImgURL" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.ImgURL" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.Budget" class="form-label-add-edit">Movie Budget</label>
                <input asp-for="@Model.Budget" class="form-control" aria-required="true" />
                <span asp-validation-for="@Model.Budget" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <input class="btn btn-warning mb-2 w-100 p-3 fw-bold" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Movie Hub/Views/Movie/MovieDetails.cshtml
@using Microsoft.AspNetCore.Identity;
@model MovieHub.ViewModels.MovieDetailsViewModel

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Info Table</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
            vertical-align: top; /* Align content to the top of cells */
        }

        th {
            background-color: #f2f2f2;
        }

        img {
            max-width: 100px;
            height: auto;
        }
    </style>
</head>


    <h1>Movie Information</h1>
    <table>
        <tr>
            <th>Title</th>
            <td>@Model.Title</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>@Model.Description</td>
        </tr>
        <tr>
            <th>Budget</th>
            <td>@Model.Budget</td>
        </tr>
        <tr>
            <th>Image</th>
            <td><img src="@Model.ImgURL" alt="Movie Poster"></td>
        </tr>
        <tr>
            <th>Release Date</th>
            <td>@Model.ReleaseDate</td>
        </tr>
        <tr>
            <th>Length</th>
            <td>@Model.MovieLength</td>
        </tr>
        <tr>
            <th>Actors</th>
            <td>
                @foreach (var actor in Model.MovieActors)
                {
                    <a asp-controller="Actor" asp-action="ActorDetails" asp-route-id="@actor.ActorId" class="btn btn-warning mb-2 w-100 p-3 fw-bold">@actor.Actor.FirstName @actor.Actor.LastName</a>
                }
            @if (User.IsInRole(AdminRole))
            {
                <a asp-controller="Actor" asp-action="AddActor" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Add actor</a>
            }
                 
            </td>
        </tr>
        <tr>
            <th>Directors</th>
            <td>
                @foreach (var actor in Model.MovieDirectors)
                {
                    <a asp-controller="Director" asp-action="DirectorDetails" asp-route-id="@actor.DirectorId" class="btn btn-warning mb-2 w-100 p-3 fw-bold">@actor.Director.FirstName @actor.Director.LastName</a>
                }
            @if (User.IsInRole(AdminRole))
            {
                
                <a asp-controller="Director" asp-action="AddDirector" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Add director</a>
            }
                 
             </td>
        </tr>
        <tr>
            <th>Categories</th>
            <td>
                <ul>
                    @foreach (var category in Model.Categories)
                    {
                        if (category != null)
                        {
                            <li>@category.Category.Name</li>
                        }
                    }
                </ul>
               
                 
             </td>
        </tr>
        <tr>
            <th>Awards</th>
            <td>
                <ul>
                    @foreach (var award in Model.Rewards)
                    {
                        if (award != null)
                        {
                            <li>@award.Title</li>
                        }
                    }
                </ul>
               
                 
             </td>
        </tr>
    </table>
@if (User.IsInRole(AdminRole))
{

    
    <a asp-controller="Movie" asp-action="DeleteMovie" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Delete movie</a>
}
      
       <a asp-controller="Movie" asp-action="Like" asp-route-id="@Model.Id" class="btn btn-warning mb-2 w-100 p-3 fw-bold">Like movie</a>